# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fef735045e9a2b34817cad8dad116bed3a3c36fd0521395867dd06e50056b81ee3333adb868962b12ca77068f29f9502ffdce5d1534164a2d4c8ba238bf98446

test:
  secret_key_base: 9c9c267a6d3030dd724a31bb0c0098649e14c3742e1b32137f378709e6aabf5dfc6b8d46e5842aacda2acd373e92d1fabdfb6278ecc5c1fd03963257651ed2c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
